### ISSUE TITLE
Firestore rules testing error on CI

### ISSUE THREAD

**Issue by alexander7161** [firebase/firebase-js-sdk#2090]
I followed the firestore rules testing tutorial and the tests work on my local machine.

However, when running with pipelines on bitbucket I get this error:

```bash
yarn run v1.15.2
$ mocha --timeout=10000
  1) "before all" hook
View rule coverage information at http://localhost:8000/emulator/v1/projects/firestore-emulator-example:ruleCoverage.html
View rule coverage information at http://localhost:8000/emulator/v1/projects/firestore-emulator-example:ruleCoverage.html
View rule coverage information at http://localhost:8000/emulator/v1/projects/firestore-emulator-example:ruleCoverage.html
  0 passing (28ms)
  1 failing
  1) "before all" hook:
     Error: 14 UNAVAILABLE: failed to connect to all addresses
      at Object.exports.createStatusError (node_modules/grpc/src/common.js:91:15)
      at Object.onReceiveStatus (node_modules/grpc/src/client_interceptors.js:1204:28)
      at InterceptingListener._callNext (node_modules/grpc/src/client_interceptors.js:568:42)
      at InterceptingListener.onReceiveStatus (node_modules/grpc/src/client_interceptors.js:618:8)
      at callback (node_modules/grpc/src/client_interceptors.js:845:24)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

My config looks like this:

```
# This is a sample build configuration for JavaScript.
# Check our guides at https://confluence.atlassian.com/x/14UWN for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: node:8.16.0
pipelines:
  default:
    - parallel: # these 2 steps will run in parallel
        - step:
            caches:
              - node
            script: # Modify the commands below to build your repository.
              - cd firestoreRules
              - yarn install
              - yarn test
        - step:
            caches:
              - node
            script:
              - cd functions
              - yarn install
              - yarn test
```
